### ISSUE TITLE
next-auth demo example throws an error after completing instruction

### ISSUE THREAD

**Issue by kouliavtsev** [manzoorwanijk/telegram-auth#12]
**Describe the bug**
After following all the steps in the [next-auth example](https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth) an authentication error is thrown, instead loging in.

**To Reproduce**
Reproduce all the steps in the [next-auth example](https://github.com/manzoorwanijk/telegram-auth/tree/main/examples/next-auth).

**Expected behavior**
User should login, or get an explicit error that could help with debugging.

**Screenshots**
<img width="1470" alt="Screenshot 2023-07-06 at 14 06 29" src="https://github.com/manzoorwanijk/telegram-auth/assets/1392575/ecb80b23-ea8b-46d5-af74-cf8d6958cc7d">

**Comment by manzoorwanijk** [comment]
@kouliavtsev Thank you for reporting the issue.

I tested it on my end just now and it works fine

<img width="382" alt="image" src="https://github.com/manzoorwanijk/telegram-auth/assets/18226415/0d169888-c013-45e2-babf-5a476f5a8d83">

Did you set the correct bot token and the corresponding bot username in `.env.local`?

**Comment by kouliavtsev** [comment]
@manzoorwanijk 

I am super sorry, I had many example open and it seemes I had copied the wrong token. Which I double checked multiple times if I copied it correctly. 😅

Thank you for writing this authentication package! 🙏
