### ISSUE TITLE
Support for Next.js App Router?

### ISSUE THREAD

**Issue by benmgreene** [manzoorwanijk/telegram-auth#13]
Hi Manzoor - this library is terrific, thank you for putting it together. I was able to get the next-auth example running quickly and easily.

Unfortunately, integrating it into my new Next.js project has been more difficult.

Would it be possible to either update the library to support Next.js 13.4+ w/ App Router, or if no updates are required, either update or duplicate the next-auth example?

Thanks again!

**Comment by manzoorwanijk** [comment]
I haven't yet tested it with the latest Next with App Router. I'll try to do it ASAP.

Thank you for reporting.

**Comment by manzoorwanijk** [comment]
I am sorry but I am still not able to get the App Router working. It is highly unstable and has lots of build errors for me. It should work the same way as explained here https://next-auth.js.org/configuration/initialization#route-handlers-app
