### ISSUE TITLE
Conditional rendering breaks

### ISSUE THREAD

**Issue by Sveagruva** [manzoorwanijk/telegram-auth#27]
**Describe the bug**
If you don't put LoginButton into it's own container and try to conditionally render, it will stay after the first render forever.

**To Reproduce**
1. Create a conditional render and render LoginButton
2. Change condition

**Expected behavior**
Not rendering LoginButton results in no button

```
  const [click, setClick] = useState(false);

return ( 
<>
<Button onClick={() => setClick((v) => !v)}>
  click
</Button>
{
  click ?
    <Button>
      Feed
    </Button> :
    <LoginButton
      botUsername={}
      authCallbackUrl={}
      buttonSize="large"
      cornerRadius={5}
      showAvatar={false}
    />
}
</>
)

```

<img width="262" alt="Screenshot 2024-08-30 at 10 13 18 AM" src="https://github.com/user-attachments/assets/083ca701-2044-4552-89d8-714b7301244f">

**Comment by manzoorwanijk** [comment]
Thank you for reporting the issue. #28 should fix it.
