### ISSUE TITLE
Button can't be rendered in more than one place at a time

### ISSUE THREAD

**Issue by nikolayemrikh** [manzoorwanijk/telegram-auth#31]
**Describe the bug**
Button can't be rendered in more than one place at a time

Use case: show the button in a sidebar and in a drawer that opens on click

**To Reproduce**
Mount LoginButton in 2 places

```tsx
<Flex vertical>
  <LoginButton botUsername={TG_DOMAIN} cornerRadius={10} onAuthCallback={(s) => mutation.mutate(s)} />
  <LoginButton botUsername={TG_DOMAIN} cornerRadius={10} onAuthCallback={(s) => mutation.mutate(s)} />
</Flex>
```

**Expected behavior**
2 buttons should be rendered. Instead, rendered only the first

**Screenshots**
<img width="614" alt="Screenshot 2024-10-06 at 17 48 18" src="https://github.com/user-attachments/assets/5e775a2c-856c-4540-bb79-611e362f21bd">

<img width="898" alt="Screenshot 2024-10-06 at 17 48 05" src="https://github.com/user-attachments/assets/d41b1c8f-c715-4284-a7a8-c161efd62632">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1 (23E224)
 - Browser: Chrome Version 129.0.6668.71 (Official Build) (arm64)

**Comment by manzoorwanijk** [comment]
That's by design from Telegram. Even if you use their script directly in a HTML page, it will be rendered only once.
